/**
* # Terradocs
* Below are the details that are generated by Terradocs plugin. It contains information about the module, inputs, outputs etc.
*
*
*/

resource "azurerm_mssql_server" "sql_server" {
  name                                 = var.sql_server_name
  resource_group_name                  = var.resource_group.name
  location                             = var.resource_group.location
  version                              = var.sql_server_version
  administrator_login                  = var.administrator_login_username
  administrator_login_password         = var.administrator_login_password
  minimum_tls_version                  = var.minimum_tls_version
  connection_policy                    = var.connection_policy
  public_network_access_enabled        = var.public_network_access_enabled
  outbound_network_restriction_enabled = var.outbound_network_restriction_enabled

  dynamic "identity" {
    for_each = var.enable_system_managed_identity ? toset(["SystemAssigned"]) : toset([])
    content {
      type = identity.value
    }
  }

  lifecycle {
    ignore_changes = [administrator_login_password]
  }

  tags = merge(local.tags)
}

resource "azurerm_mssql_server_extended_auditing_policy" "server_auditing_policy" {
  count                                   = var.extended_auditing_enabled ? 1 : 0
  server_id                               = azurerm_mssql_server.sql_server.id
  retention_in_days                       = var.retention_in_days
  storage_account_access_key              = var.storage_account_access_key
  storage_account_access_key_is_secondary = false
  storage_endpoint                        = var.storage_endpoint
}
